import type { RateLimitPolicy } from "./types";

const MINUTE = 60_000;
const HOUR = 60 * MINUTE;

export const RATE_LIMIT_POLICIES = {
  loginIp: {
    id: "login-ip",
    purpose: "login",
    algorithm: "sliding-window",
    limit: 10,
    window: "15 m",
    windowMs: 15 * MINUTE,
    failureMode: "closed",
  },
  loginEmail: {
    id: "login-email",
    purpose: "login",
    algorithm: "sliding-window",
    limit: 10,
    window: "15 m",
    windowMs: 15 * MINUTE,
    failureMode: "closed",
  },
  forgotPasswordIp: {
    id: "forgot-password-ip",
    purpose: "forgot-password",
    algorithm: "sliding-window",
    limit: 5,
    window: "30 m",
    windowMs: 30 * MINUTE,
    failureMode: "acknowledge",
  },
  forgotPasswordIdentity: {
    id: "forgot-password-identity",
    purpose: "forgot-password",
    algorithm: "sliding-window",
    limit: 5,
    window: "30 m",
    windowMs: 30 * MINUTE,
    failureMode: "acknowledge",
  },
  resetPasswordIp: {
    id: "reset-password-ip",
    purpose: "reset-password",
    algorithm: "sliding-window",
    limit: 5,
    window: "30 m",
    windowMs: 30 * MINUTE,
    failureMode: "closed",
  },
  changePasswordUser: {
    id: "change-password-user",
    purpose: "change-password",
    algorithm: "sliding-window",
    limit: 5,
    window: "30 m",
    windowMs: 30 * MINUTE,
    failureMode: "closed",
  },
  importClient: {
    id: "import-client",
    purpose: "lead-import",
    algorithm: "fixed-window",
    limit: 120,
    window: "5 m",
    windowMs: 5 * MINUTE,
    failureMode: "closed",
  },
  acquisitionGetClient: {
    id: "acquisition-get-client",
    purpose: "acquisition-job-get",
    algorithm: "fixed-window",
    limit: 60,
    window: "15 m",
    windowMs: 15 * MINUTE,
    failureMode: "open",
  },
  acquisitionPatchClient: {
    id: "acquisition-patch-client",
    purpose: "acquisition-job-patch",
    algorithm: "fixed-window",
    limit: 60,
    window: "15 m",
    windowMs: 15 * MINUTE,
    failureMode: "closed",
  },
  acquisitionPatchJob: {
    id: "acquisition-patch-job",
    purpose: "acquisition-job-patch",
    algorithm: "fixed-window",
    limit: 15,
    window: "15 m",
    windowMs: 15 * MINUTE,
    failureMode: "closed",
  },
  acquisitionActionUser: {
    id: "acquisition-action-user",
    purpose: "acquisition-action",
    algorithm: "fixed-window",
    limit: 3,
    window: "1 h",
    windowMs: HOUR,
    failureMode: "closed",
  },
} as const satisfies Record<string, RateLimitPolicy>;
